# Generated by Django 4.1.2 on 2022-10-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryList',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='featured_image',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
