# Generated by Django 4.1.2 on 2022-10-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_gallery_product_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.FileField(default='a', upload_to='products/media/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='products_category',
        ),
        migrations.AlterModelTable(
            name='gallery',
            table='products_gallery',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products_product',
        ),
    ]
