# Generated by Django 4.1.2 on 2022-10-18 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_category_image_category_image_gallery_image_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gallery',
            table='product_gallery',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product_product',
        ),
    ]
