# Generated by Django 4.1.2 on 2022-10-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_gallery_table_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gallery',
            table='products_gallery',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products_product',
        ),
    ]
