# Generated by Django 4.1.2 on 2022-10-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_gallery_table_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='gallery',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
