# Generated by Django 4.1.2 on 2022-10-18 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_category_table_alter_gallery_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='products_category',
        ),
        migrations.AlterModelTable(
            name='gallery',
            table='products_gallery',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products_product',
        ),
    ]
