# Generated by Django 4.1.2 on 2022-10-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_image_category_category_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_image',
            new_name='image',
        ),
    ]
